# Generated by Django 4.2 on 2024-05-26 07:13

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import web.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('rut', models.CharField(max_length=10, verbose_name='RUT')),
                ('direccion', models.CharField(blank=True, max_length=50, verbose_name='Direccion')),
                ('telefono_personal', models.IntegerField(blank=True, verbose_name='Telefono Personal')),
                ('tipo_de_usuario', models.CharField(choices=[('arrendatario', 'arrendatario'), ('arrendador', 'arrendador')], default='arrendador')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('m2_construidos', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Metros² Construidos')),
                ('m2_totales', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Metros² Totales o del terreno')),
                ('estacionamientos', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de estacionamientos')),
                ('habitaciones', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de habitaciones')),
                ('restrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de baños')),
                ('direccion', models.CharField(blank=True, max_length=50, verbose_name='Direccion')),
                ('comuna', models.CharField(choices=[('Santiago', 'Santiago'), ('La Florida', 'La Florida'), ('Maipú', 'Maipú'), ('Las Condes', 'Las Condes'), ('Puente Alto', 'Puente Alto'), ('San Bernardo', 'San Bernardo'), ('La Pintana', 'La Pintana'), ('Quilicura', 'Quilicura'), ('Recoleta', 'Recoleta'), ('Providencia', 'Providencia'), ('La Reina', 'La Reina'), ('Peñaflor', 'Peñaflor'), ('Renca', 'Renca'), ('San Ramón', 'San Ramón'), ('Ñuñoa', 'Ñuñoa'), ('El Bosque', 'El Bosque'), ('Independencia', 'Independencia'), ('Huechuraba', 'Huechuraba'), ('Colina', 'Colina'), ('Padre Hurtado', 'Padre Hurtado'), ('Lo Barnechea', 'Lo Barnechea'), ('Lo Espejo', 'Lo Espejo'), ('Lo Prado', 'Lo Prado'), ('Macul', 'Macul'), ('Conchalí', 'Conchalí'), ('Cerrillos', 'Cerrillos'), ('Cerro Navia', 'Cerro Navia'), ('Estación Central', 'Estación Central'), ('Pedro Aguirre Cerda', 'Pedro Aguirre Cerda'), ('Peñalolén', 'Peñalolén'), ('Pirque', 'Pirque'), ('San Joaquín', 'San Joaquín'), ('San José de Maipo', 'San José de Maipo'), ('San Miguel', 'San Miguel'), ('Santa Cruz', 'Santa Cruz'), ('Talagante', 'Talagante'), ('Vitacura', 'Vitacura'), ('La Granja', 'La Granja'), ('Paine', 'Paine'), ('Alhué', 'Alhué'), ('Buin', 'Buin'), ('Calera de Tango', 'Calera de Tango'), ('Curacaví', 'Curacaví'), ('Lampa', 'Lampa'), ('María Pinto', 'María Pinto'), ('Melipilla', 'Melipilla'), ('Til Til', 'Til Til'), ('Pudahuel', 'Pudahuel'), ('Quinta Normal', 'Quinta Normal'), ('Arica', 'Arica'), ('Camarones', 'Camarones'), ('General Lagos', 'General Lagos'), ('Putre', 'Putre'), ('Iquique', 'Iquique'), ('Alto Hospicio', 'Alto Hospicio'), ('Camiña', 'Camiña'), ('Colchane', 'Colchane'), ('Huara', 'Huara'), ('Pica', 'Pica'), ('Pozo Almonte', 'Pozo Almonte'), ('Antofagasta', 'Antofagasta'), ('Mejillones', 'Mejillones'), ('Sierra Gorda', 'Sierra Gorda'), ('Taltal', 'Taltal'), ('Calama', 'Calama'), ('Ollagüe', 'Ollagüe'), ('San Pedro de Atacama', 'San Pedro de Atacama'), ('Tocopilla', 'Tocopilla'), ('María Elena', 'María Elena'), ('Copiapó', 'Copiapó'), ('Caldera', 'Caldera'), ('Tierra Amarilla', 'Tierra Amarilla'), ('Chañaral', 'Chañaral'), ('Diego de Almagro', 'Diego de Almagro'), ('Vallenar', 'Vallenar'), ('Alto del Carmen', 'Alto del Carmen'), ('Freirina', 'Freirina'), ('Huasco', 'Huasco'), ('La Serena', 'La Serena'), ('Coquimbo', 'Coquimbo'), ('Andacollo', 'Andacollo'), ('La Higuera', 'La Higuera'), ('Paiguano', 'Paiguano'), ('Vicuña', 'Vicuña'), ('Illapel', 'Illapel'), ('Canela', 'Canela'), ('Los Vilos', 'Los Vilos'), ('Salamanca', 'Salamanca'), ('Ovalle', 'Ovalle'), ('Combarbalá', 'Combarbalá'), ('Monte Patria', 'Monte Patria'), ('Punitaqui', 'Punitaqui'), ('Río Hurtado', 'Río Hurtado'), ('Valparaíso', 'Valparaíso'), ('Casablanca', 'Casablanca'), ('Concón', 'Concón'), ('Juan Fernández', 'Juan Fernández'), ('Puchuncaví', 'Puchuncaví'), ('Quintero', 'Quintero'), ('Viña del Mar', 'Viña del Mar'), ('Isla de Pascua', 'Isla de Pascua'), ('Los Andes', 'Los Andes'), ('Calle Larga', 'Calle Larga'), ('Rinconada', 'Rinconada'), ('San Esteban', 'San Esteban'), ('La Ligua', 'La Ligua'), ('Cabildo', 'Cabildo'), ('Papudo', 'Papudo'), ('Petorca', 'Petorca'), ('Zapallar', 'Zapallar'), ('Quillota', 'Quillota'), ('La Calera', 'La Calera'), ('Hijuelas', 'Hijuelas'), ('La Cruz', 'La Cruz'), ('Nogales', 'Nogales'), ('San Antonio', 'San Antonio'), ('Algarrobo', 'Algarrobo'), ('Cartagena', 'Cartagena'), ('El Quisco', 'El Quisco'), ('El Tabo', 'El Tabo'), ('Santo Domingo', 'Santo Domingo'), ('San Felipe', 'San Felipe'), ('Catemu', 'Catemu'), ('Llaillay', 'Llaillay'), ('Panquehue', 'Panquehue'), ('Putaendo', 'Putaendo'), ('Santa María', 'Santa María'), ('Quilpué', 'Quilpué'), ('Limache', 'Limache'), ('Olmué', 'Olmué'), ('Villa Alemana', 'Villa Alemana'), ('Rancagua', 'Rancagua'), ('Codegua', 'Codegua'), ('Coinco', 'Coinco'), ('Coltauco', 'Coltauco'), ('Doñihue', 'Doñihue'), ('Graneros', 'Graneros'), ('Las Cabras', 'Las Cabras'), ('Machalí', 'Machalí'), ('Malloa', 'Malloa'), ('Mostazal', 'Mostazal'), ('Olivar', 'Olivar'), ('Peumo', 'Peumo'), ('Pichidegua', 'Pichidegua'), ('Quinta de Tilcoco', 'Quinta de Tilcoco'), ('Requínoa', 'Requínoa'), ('Rengo', 'Rengo'), ('San Vicente', 'San Vicente'), ('Pichilemu', 'Pichilemu'), ('La Estrella', 'La Estrella'), ('Litueche', 'Litueche'), ('Marchihue', 'Marchihue'), ('Navidad', 'Navidad'), ('Paredones', 'Paredones'), ('San Fernando', 'San Fernando'), ('Chimbarongo', 'Chimbarongo'), ('Lolol', 'Lolol'), ('Nancagua', 'Nancagua'), ('Palmilla', 'Palmilla'), ('Peralillo', 'Peralillo'), ('Placilla', 'Placilla'), ('Pumanque', 'Pumanque'), ('Curicó', 'Curicó'), ('Hualañé', 'Hualañé'), ('Licantén', 'Licantén'), ('Molina', 'Molina'), ('Rauco', 'Rauco'), ('Romeral', 'Romeral'), ('Sagrada Familia', 'Sagrada Familia'), ('Teno', 'Teno'), ('Vichuquén', 'Vichuquén'), ('Talca', 'Talca'), ('Constitución', 'Constitución'), ('Curepto', 'Curepto'), ('Empedrado', 'Empedrado'), ('Maule', 'Maule'), ('Pelarco', 'Pelarco'), ('Pencahue', 'Pencahue'), ('Río Claro', 'Río Claro'), ('San Clemente', 'San Clemente'), ('San Rafael', 'San Rafael'), ('Linares', 'Linares'), ('Colbún', 'Colbún'), ('Longaví', 'Longaví'), ('Parral', 'Parral'), ('Retiro', 'Retiro'), ('San Javier', 'San Javier'), ('Villa Alegre', 'Villa Alegre'), ('Yerbas Buenas', 'Yerbas Buenas'), ('Cauquenes', 'Cauquenes'), ('Chanco', 'Chanco'), ('Pelluhue', 'Pelluhue'), ('Chillán', 'Chillán'), ('Bulnes', 'Bulnes'), ('Coihueco', 'Coihueco'), ('El Carmen', 'El Carmen'), ('Pemuco', 'Pemuco'), ('Pinto', 'Pinto'), ('Quillón', 'Quillón'), ('San Ignacio', 'San Ignacio'), ('Yungay', 'Yungay'), ('Quirihue', 'Quirihue'), ('Cobquecura', 'Cobquecura'), ('Ninhue', 'Ninhue'), ('Treguaco', 'Treguaco'), ('San Carlos', 'San Carlos'), ('Ñuble', 'Ñuble'), ('San Nicolás', 'San Nicolás'), ('Concepción', 'Concepción'), ('Coronel', 'Coronel'), ('Chiguayante', 'Chiguayante'), ('Florida', 'Florida'), ('Hualqui', 'Hualqui'), ('Lota', 'Lota'), ('Penco', 'Penco'), ('San Pedro de la Paz', 'San Pedro de la Paz'), ('Santa Juana', 'Santa Juana'), ('Talcahuano', 'Talcahuano'), ('Tomé', 'Tomé'), ('Hualpén', 'Hualpén'), ('Lebu', 'Lebu'), ('Arauco', 'Arauco'), ('Cañete', 'Cañete'), ('Contulmo', 'Contulmo'), ('Curanilahue', 'Curanilahue'), ('Los Álamos', 'Los Álamos'), ('Tirúa', 'Tirúa'), ('Los Ángeles', 'Los Ángeles'), ('Antuco', 'Antuco'), ('Cabrero', 'Cabrero'), ('Laja', 'Laja'), ('Mulchén', 'Mulchén'), ('Nacimiento', 'Nacimiento'), ('Negrete', 'Negrete'), ('Quilleco', 'Quilleco'), ('San Rosendo', 'San Rosendo'), ('Santa Bárbara', 'Santa Bárbara'), ('Tucapel', 'Tucapel'), ('Yumbel', 'Yumbel'), ('Alto Biobío', 'Alto Biobío'), ('Temuco', 'Temuco'), ('Carahue', 'Carahue'), ('Cunco', 'Cunco'), ('Curarrehue', 'Curarrehue'), ('Freire', 'Freire'), ('Galvarino', 'Galvarino'), ('Gorbea', 'Gorbea'), ('Lautaro', 'Lautaro'), ('Loncoche', 'Loncoche'), ('Melipeuco', 'Melipeuco'), ('Nueva Imperial', 'Nueva Imperial'), ('Padre Las Casas', 'Padre Las Casas'), ('Perquenco', 'Perquenco'), ('Pitrufquén', 'Pitrufquén'), ('Pucón', 'Pucón'), ('Saavedra', 'Saavedra'), ('Teodoro Schmidt', 'Teodoro Schmidt'), ('Toltén', 'Toltén'), ('Vilcún', 'Vilcún'), ('Villarrica', 'Villarrica'), ('Cholchol', 'Cholchol'), ('Angol', 'Angol'), ('Collipulli', 'Collipulli'), ('Curacautín', 'Curacautín'), ('Ercilla', 'Ercilla'), ('Lonquimay', 'Lonquimay'), ('Los Sauces', 'Los Sauces'), ('Lumaco', 'Lumaco'), ('Purén', 'Purén'), ('Renaico', 'Renaico'), ('Traiguén', 'Traiguén'), ('Victoria', 'Victoria'), ('Corral', 'Corral'), ('Lanco', 'Lanco'), ('Los Lagos', 'Los Lagos'), ('Máfil', 'Máfil'), ('Mariquina', 'Mariquina'), ('Paillaco', 'Paillaco'), ('Panguipulli', 'Panguipulli'), ('La Unión', 'La Unión'), ('Futrono', 'Futrono'), ('Lago Ranco', 'Lago Ranco'), ('Río Bueno', 'Río Bueno'), ('Puerto Montt', 'Puerto Montt'), ('Calbuco', 'Calbuco'), ('Cochamó', 'Cochamó'), ('Fresia', 'Fresia'), ('Frutillar', 'Frutillar'), ('Los Muermos', 'Los Muermos'), ('Llanquihue', 'Llanquihue'), ('Maullín', 'Maullín'), ('Puerto Varas', 'Puerto Varas'), ('Castro', 'Castro'), ('Ancud', 'Ancud'), ('Chonchi', 'Chonchi'), ('Curaco de Vélez', 'Curaco de Vélez'), ('Dalcahue', 'Dalcahue'), ('Puqueldón', 'Puqueldón'), ('Queilén', 'Queilén'), ('Quellón', 'Quellón'), ('Quemchi', 'Quemchi'), ('Quinchao', 'Quinchao'), ('Osorno', 'Osorno'), ('Puerto Octay', 'Puerto Octay'), ('Purranque', 'Purranque'), ('Puyehue', 'Puyehue'), ('Río Negro', 'Río Negro'), ('San Juan de la Costa', 'San Juan de la Costa'), ('San Pablo', 'San Pablo'), ('Chaitén', 'Chaitén'), ('Futaleufú', 'Futaleufú'), ('Hualaihué', 'Hualaihué'), ('Palena', 'Palena'), ('Coyhaique', 'Coyhaique'), ('Lagos del Mont', 'Lagos del Mont'), ('Aysén', 'Aysén'), ('Cisnes', 'Cisnes'), ('Guaitecas', 'Guaitecas'), ('Cochrane', 'Cochrane'), ("O'Higgins", "O'Higgins"), ('Tortel', 'Tortel'), ('Chile Chico', 'Chile Chico'), ('Río Ibáñez', 'Río Ibáñez'), ('Punta Arenas', 'Punta Arenas'), ('Laguna Blanca', 'Laguna Blanca'), ('Río Verde', 'Río Verde'), ('San Gregorio', 'San Gregorio'), ('Cabo de Hornos', 'Cabo de Hornos'), ('Antártica', 'Antártica'), ('Porvenir', 'Porvenir'), ('Primavera', 'Primavera'), ('Timaukel', 'Timaukel'), ('Natales', 'Natales'), ('Torres del Paine', 'Torres del Paine'), ('Colchagua', 'Colchagua'), ('Valdivia', 'Valdivia')], default='Santiago', verbose_name='Comuna')),
                ('tipo_de_inmueble', models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento'), ('Parcela', 'Parcela')], default='Casa')),
                ('arriendo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio mensual de arriendo')),
                ('arrendador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inmueble_arrendador', to=settings.AUTH_USER_MODEL, validators=[web.validators.TipoUsuarioValidator(foreing_key_field='arrendador', related_field='tipo_de_usuario', tipos_de_usuario=['arrendador'])])),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inmueble_arrendatario', to=settings.AUTH_USER_MODEL, validators=[web.validators.TipoUsuarioValidator(foreing_key_field='arrendatario', related_field='tipo_de_usuario', tipos_de_usuario=['arrendatario'])])),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudArriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptada', models.BooleanField(default=False)),
                ('arrendador', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Arrendador')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.inmueble', verbose_name='Inmueble')),
            ],
        ),
    ]
