# Generated by Django 4.2 on 2024-05-26 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_usuario_tipo_de_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono_personal',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Telefono Personal'),
        ),
    ]
