# Generated by Django 4.2 on 2024-05-26 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_usuario_groups_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='arrendador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inmueble_arrendador', to=settings.AUTH_USER_MODEL, validators=[web.validators.TipoUsuarioValidator(foreing_key_field='arrendador', related_field='tipo_de_usuario', tipos_de_usuario=['arrendador'])]),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='arrendatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inmueble_arrendatario', to=settings.AUTH_USER_MODEL, validators=[web.validators.TipoUsuarioValidator(foreing_key_field='arrendatario', related_field='tipo_de_usuario', tipos_de_usuario=['arrendatario'])]),
        ),
    ]
