# Generated by Django 4.2 on 2024-05-27 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_inmueble_arrendador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='arriendo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio mensual de arriendo'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='estacionamientos',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de estacionamientos'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='habitaciones',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de habitaciones'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='restrooms',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de baños'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono_personal',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Telefono Personal'),
        ),
    ]
