# Generated by Django 4.2 on 2024-05-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_usuario_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Esta el usuario activo?'),
        ),
    ]
