# Generated by Django 4.2 on 2024-05-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_usuario_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
