# Generated by Django 4.2 on 2024-05-30 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_usuario_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Contraseña'),
        ),
    ]
