# Generated by Django 4.2 on 2024-05-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_usuario_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('customer_name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('message', models.TextField(verbose_name='Mensaje')),
            ],
        ),
    ]
