# Generated by Django 4.2 on 2024-05-31 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_contactrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='arrendatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inmueble_arrendatario', to=settings.AUTH_USER_MODEL),
        ),
    ]
