FROM python:3.12.4-alpine3.20

# Set working directory
# RUN mkdir -p /usr/inmuebles

WORKDIR /usr/inmuebles

# New User
RUN adduser -D hlata
# RUN adduser hlata sudo
# RUN grep sudo /etc/group

#RUN adduser -D $USER && mkdir -p /etc/sudoers.d \
        #&& echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER \
        #&& chmod 0440 /etc/sudoers.d/$USER

# Copy data
COPY ./requirements.txt ./
COPY ./inmuebles/ ./

# Update Linux and install dependencies
RUN apk update && apk upgrade && apk add --no-cache make g++ openssh libpq-dev postgresql-dev postgresql postgresql-contrib curl

# Install pip packages
RUN pip install -r requirements.txt

# Load Postgresql data
RUN python manage.py migrate
RUN python manage.py loaddata web/fixtures/regiones.json
RUN python manage.py loaddata web/fixtures/comunas.json
RUN python manage.py loaddata web/fixtures/tipos_usuarios.json
RUN python manage.py loaddata web/fixtures/tipos_inmuebles.json
RUN python manage.py loaddata web/fixtures/usuarios.json
RUN python manage.py loaddata web/fixtures/inmuebles.json 
RUN python manage.py loaddata web/fixtures/solicitudes_arriendo.json

# Load Statics
RUN python manage.py collectstatic --noinput

# Expose the listening port
EXPOSE 80

# Change user
USER hlata

# Launch app
# RUN gunicorn inmuebles.wsgi --bind=0.0.0.0:80 
CMD [ "gunicorn", "--bind", "0.0.0.0:80", "inmuebles.wsgi:application"]