class RegionChoices (models.TextChoices):
    ARICA_Y_PARINACOTA = "Arica y Parinacota", "Arica y Parinacota"
    TARAPACA = "Tarapacá", "Tarapacá"
    ANTOFAGASTA = "Antofagasta", "Antofagasta"
    ATACAMA = "Atacama", "Atacama"
    COQUIMBO = "Coquimbo", "Coquimbo"
    VALPARAISO = "Valparaíso", "Valparaíso"
    REGION_DEL_LIBERTADOR_GRAL_BERNARDO_OHIGGINS = "Región del Libertador Gral. Bernardo O’Higgins", "Región del Libertador Gral. Bernardo O’Higgins"
    REGION_DEL_MAULE = "Región del Maule", "Región del Maule"
    REGION_DE_NUBLE = "Región de Ñuble", "Región de Ñuble"
    REGION_DEL_BIOBIO = "Región del Biobío", "Región del Biobío"
    REGION_DE_LA_ARAUCANIA = "Región de la Araucanía", "Región de la Araucanía"
    REGION_DE_LOS_RIOS = "Región de Los Ríos", "Región de Los Ríos"
    REGION_DE_LOS_LAGOS = "Región de Los Lagos", "Región de Los Lagos"
    REGION_AISEN_DEL_GRAL_CARLOS_IBANEZ_DEL_CAMPO = "Región Aisén del Gral. Carlos Ibáñez del Campo", "Región Aisén del Gral. Carlos Ibáñez del Campo"
    REGION_DE_MAGALLANES_Y_DE_LA_ANTARTICA_CHILENA = "Región de Magallanes y de la Antártica Chilena", "Región de Magallanes y de la Antártica Chilena"
    REGION_METROPOLITANA_DE_SANTIAGO = "Región Metropolitana de Santiago", "Región Metropolitana de Santiago"
